# @package _global_

test: True
copy_cache: False
resume: False

trainer:
  fast_dev_run: 2
  # max_epochs: 1
  # accelerator: cpu
  # devices: 1
  devices: 1
  strategy: auto
  # auto_select_gpus: True
  enable_checkpointing: False
  logger:
    save_dir: log/test

# dataloader:
#   batch_size: 32