# @package _global_

model:
  _target_: src.model.eae.LitEquivariantAE
  latent_dim: 128
  num_patches: 196
  enc_embed_dim: 768
  dec_embed_dim: 256
  latent_pooling: average
  adapter: lowrank

  encoder:
    _target_: src.model.network.ViTEncoder
    img_size: 224
    patch_size: 16
    mlp_ratio: 4
    depth: 12
    embed_dim: ${model.enc_embed_dim}
    num_heads: 12
    img_channels: 3
    dualnorm: True

  decoder:
    _target_: src.model.network.ViTDecoder
    img_size: ${model.encoder.img_size}
    patch_size: ${model.encoder.patch_size}
    mlp_ratio: ${model.encoder.mlp_ratio}
    depth: 6
    embed_dim: ${model.dec_embed_dim}
    num_heads: 8
    img_channels: ${model.encoder.img_channels}