batchsize: &nbat 16
seed: 1
max_iteration: &itr 100000
report_freq: 500
model_snapshot_freq: *itr
manager_snapshot_freq: *itr
num_workers: 2
T_cond: 4
T_pred: 2
lr: 0.0001
gpu_id: &gid 0

fixedM: True

train_data:
  fn: ./period_fn.py
  name: Shifted_FixedFreqFun_nl
  args:
    Ndata: &ndat 5000
    T: 6
    max_T: 9
    shift_label: True   # Set True if Fixed model is used
    indexing: False   # Set Trie if indices of data should be assigned
    shift_range: 2
    batchM_size: *nbat
    nfreq: 5
    ns: 0.1

model:
  fn: ./models/seqae.py
  name: SeqAETSQmlp 
  args:
    dim_a: 32
    dim_m: 1
    enc_hdim: 256
    dec_hdim: 256
    coef_internal: 1.0
    predictive: True
    optMg_loss: False    # add loss for optimized M(g).   
    gpu_id: *gid
    transition_model: Fixed  # either of LS, Fixed, MgDGD, NNg, NNgi, gopt
    second_transition: 


training_loop:
  fn: ./training_loops.py
  name: loop_seqmodel
  args:
    lr_decay_iter: 40000
    lr_decay_ratio: 5.0
    lr_decay_iter1: 40000
    lr_decay_iter2: 80000
    lr_decay_ratio1: 5.0
    lr_decay_ratio2: 3.0
    reconst_iter: *itr



